routes/web.php
<?php

Route::resource('power_unit', 'PowerUnitController');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/test', 'HomeController@test')->name('test');

app/Models/PowerUnit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PowerUnit extends Model
{
  protected $table = 'power_unit';
  protected $guarded = ['id_power_unit'];

  protected  $primaryKey = 'id_power_unit';

  public function user()
  {
    return $this->belongsTo(User::class);
  }

  public function Location()
  {
    return $this->belongsTo('App\Models\Location','id_location','id_location');
  }

  public function Corporation()
  {
    return $this->belongsTo('App\Models\Corporation','id_corporation','id_corporation');
  }

  public function PowerUnitType()
  {
    return $this->belongsTo('App\Models\PowerUnitType','id_power_unit_type','id_power_unit_type');
  }

}

app/Models/PowerUnitType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PowerUnitType extends Model
{
  protected $table = 'power_unit_type';
  protected $guarded = ['id_power_unit_type'];

  protected  $primaryKey = 'id_power_unit_type';

  public function user()
  {
    return $this->belongsTo(User::class);
  }

  public function PowerUnit()
  {
      return $this->hasMany(PowerUnit::class);
  }
}

app/Http/Controllers/API/PowerUnitController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Requests\StoreUpdatePowerUnitFormRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\Models\PowerUnit;
use App\Models\PowerUnitType;
use App\Models\Location;
use App\Models\Corporation;
use Auth;
use Illuminate\Http\Request;
use JWTFactory;
use JWTAuth;

class PowerUnitController extends Controller
{
  private $powerUnit;

  public function __construct(PowerUnit $powerUnit)
  {
    $this->power_unit = $powerUnit;
  }

  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    try {
      $power_units = $this->power_unit->latest()->paginate();

      $this->return['status'] = 'success';
      $this->return['status_code'] = 200;
      $this->return['data'] = $power_units;
    } catch (\Exception $e) {
      $this->return['status'] = 'error';
      $this->return['status_code'] = 400;
      $this->return['message'] = [$e->getMessage()];
    }

    return response()->json($this->return);
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */

  /**
  * Store a newly created resource in storage.
  *
  * @param  \App\Http\Requests\StoreUpdatePowerUnitFormRequest  $request
  * @return \Illuminate\Http\Response
  */
  public function store(StoreUpdatePowerUnitFormRequest $request)
  {
    $data = $request->all();

    try {
      $powerUnit = new PowerUnit;
      $powerUnit->power_unit_num = $data['power_unit_num'];
      $powerUnit->description = $data['description'];
      $powerUnit->id_corporation = $data['id_corporation'];
      $powerUnit->id_location = $data['id_location'];
      $powerUnit->id_power_unit_type = $data['id_power_unit_type'];
      $powerUnit->insert_user = auth()->user()->id;
      $powerUnit->save();

      $this->return['status'] = 'success';
      $this->return['status_code'] = 200;
      $this->return['data'] = $powerUnit;
    } catch (\Exception $e) {
      $this->return['status'] = 'error';
      $this->return['status_code'] = 400;
      $this->return['message'] = [$e->getMessage()];
    }

    return response()->json($this->return);
  }
  /**
  * Update the specified resource in storage.
  *
  * @param  \App\Http\Requests\StoreUpdatePowerUnitFormRequest  $request
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function update(StoreUpdatePowerUnitFormRequest $request, $id)
  {
    if (!$powerUnit = $this->power_unit->find($id)){
      $this->return['status'] = 'error';
      $this->return['status_code'] = 400;
      $this->return['message'] = 'No record for these data';
    } else {
      try {
        $data = $request->all();
        $data['update_user'] = auth()->user()->id;

        $powerUnit->update($data);

        $this->return['status'] = 'success';
        $this->return['status_code'] = 200;
        $this->return['data'] = $data;
        $this->return['message'] = 'Update data success';
      } catch (\Exception $e) {
        $this->return['status'] = 'error';
        $this->return['status_code'] = 400;
        $this->return['message'] = [$e->getMessage()];
      }
    }
    return response()->json($this->return);
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    if (!$powerUnit = $this->power_unit->find($id)){
      $this->return['status'] = 'error';
      $this->return['status_code'] = 400;
      $this->return['message'] = 'No record for these data';
    } else {
      try {
        $powerUnit->delete();

        $this->return['status'] = 'success';
        $this->return['status_code'] = 200;
        $this->return['message'] = 'Delete data success';
      } catch (\Exception $e) {
        $this->return['status'] = 'error';
        $this->return['status_code'] = 400;
        $this->return['message'] = [$e->getMessage()];
      }
    }
    return response()->json($this->return);
  }
}

app/Http/Controllers/PowerUnitController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUpdatePowerUnitFormRequest;
use Illuminate\Support\Facades\Storage;
use App\Models\PowerUnit;
use App\Models\PowerUnitType;
use App\Models\Location;
use App\Models\Corporation;
use Auth;
use Illuminate\Http\Request;

class PowerUnitController extends Controller
{
  private $powerUnit;

  public function __construct(PowerUnit $powerUnit)
  {
    $this->power_unit = $powerUnit;

    $this->middleware('auth')
    ->except([
      'index', 'show'
    ]);
  }

  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $power_units = $this->power_unit->latest()->paginate();

    return view('power_units.index', compact('power_units'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $data['power_unit_types'] = PowerUnitType::all();
    $data['locations'] = Location::all();
    $data['corporations'] = Corporation::all();

    return view('power_units.create', compact('data'));
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \App\Http\Requests\StoreUpdatePowerUnitFormRequest  $request
  * @return \Illuminate\Http\Response
  */
  public function store(StoreUpdatePowerUnitFormRequest $request)
  {
    $data = $request->all();

    $powerUnit = new PowerUnit;
    $powerUnit->power_unit_num = $data['power_unit_num'];
    $powerUnit->description = $data['description'];
    $powerUnit->id_corporation = $data['id_corporation'];
    $powerUnit->id_location = $data['id_location'];
    $powerUnit->id_power_unit_type = $data['id_power_unit_type'];
    $powerUnit->insert_user = Auth::user()->id;
    $powerUnit->save();

    return redirect()
    ->route('power_unit.index')
    ->withSuccess('Create data success');
  }

  /**
  * Display the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function show($id)
  {
    if (!$power_unit = $this->power_unit->find($id))
    return redirect()->back();

    return view('power_units.show', compact('power_unit'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    if (!$power_unit = $this->power_unit->find($id))
    return redirect()->back();
    $data['power_unit_types'] = PowerUnitType::all();
    $data['locations'] = Location::all();
    $data['corporations'] = Corporation::all();
    $data['power_unit'] = $power_unit;

    return view('power_units.edit', compact('data'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \App\Http\Requests\StoreUpdatePowerUnitFormRequest  $request
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function update(StoreUpdatePowerUnitFormRequest $request, $id)
  {
    if (!$powerUnit = $this->power_unit->find($id))
    return redirect()->back();

    $data = $request->all();
    $data['update_user'] = Auth::user()->id;

    $powerUnit->update($data);

    return redirect()
    ->route('power_unit.index')
    ->withSuccess('Update data success!');
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    if (!$powerUnit = $this->power_unit->find($id))
    return redirect()->back();

    $powerUnit->delete();

    return redirect()
    ->route('power_unit.index')
    ->withSuccess('Delete data success!');
  }
}

resources/views/power_units/create.blade.php
@extends('layouts.app')

@section('title', 'Add New Power Unit')

@section('content')

<h1>Add Power Unit</h1>

<form action="{{ route('power_unit.store') }}" method="post" enctype="multipart/form-data">
    @include('power_units._partials.form')
</form>

@endsection

resources/views/power_units/edit.blade.php
@extends('layouts.app')

@section('title', "Edit Power Unit {$data['power_unit']->power_unit_num}")

@section('content')

<h1>Edit Power Unit: {{ $data['power_unit']->power_unit_num }}</h1>

<form action="{{ route('power_unit.update', $data['power_unit']->id_power_unit) }}" method="post" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="PUT">

    @include('power_units._partials.form')
</form>

@endsection

resources/views/power_units/index.blade.php
@extends('layouts.app')

@section('title', 'Listagem dos posts')

@section('content')

<h1>
  Power Units
  <a href="{{ route('power_unit.create') }}" class="btn btn-primary">
    <i class="fas fa-plus-square"></i>
  </a>
</h1>

@include('includes.alerts')

<ul class="media-list">
  @php
  $i = 1;
  @endphp
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Power Unit Num</th>
        <th scope="col">Description</th>
        <th scope="col">Power Unit Type</th>
        <th scope="col">Corporation</th>
        <th scope="col">Location</th>
      </tr>
    </thead>
    <tbody>
      @forelse($power_units as $power_unit)
      <tr>
        <th scope="row">{{$i}}</th>
        <td>{{$power_unit->power_unit_num}}</td>
        <td>{{$power_unit->description}}</td>
        <td>{{$power_unit->PowerUnitType->power_unit_type_xid}}</td>
        <td>{{$power_unit->Corporation->corporation_name}}</td>
        <td>{{$power_unit->Location->location_name}}</td>
        <td>
          <a href="{{ route('power_unit.destroy', $power_unit->id_power_unit) }}">Delete</a> |
          <a href="{{ route('power_unit.edit', $power_unit->id_power_unit) }}">Edit</a>
        </td>
      </tr>
      <hr>
      @php
      $i++;
      @endphp
      @empty
      <li class="media">
        <p>No Data!</p>
      </li>
      @endforelse
    </tbody>
  </table>
  {!! $power_units->links() !!}
</ul>

@endsection

resources/views/power_units/show.blade.php
@extends('layouts.app')

@section('title', ": {$power_unit->power_unit_num}")

@section('content')

<h1>Delete Power Unit <b>{{ $power_unit->power_unit_num }}</b></h1>

<p>{{ $power_unit->description }}</p>

<form action="{{ route('power_unit.destroy', $power_unit->id_power_unit) }}" method="post">
    @csrf
    <input type="hidden" name="_method" value="DELETE">
    <button type="submit" class="btn btn-danger">Delete Power Unit: {{ $power_unit->power_unit_num }}</button>
</form>

@endsection